- id: external-lb-hiera
  version: 2.0.0
  type: puppet
  groups: ['/.*/']
  requires: [hiera]
  required_for: [hiera-update]
  parameters:
    puppet_manifest: puppet/manifests/create_hiera_config.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 360

- id: hiera-update
  version: 2.0.0
  type: puppet
  groups: ['/.*/']
  requires: [external-lb-hiera]
  required_for: [globals]
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/hiera/hiera.pp
    puppet_modules: /etc/puppet/modules
    timeout: 360

- id: external-lb-ovs-to-ns-port-ocf
  version: 2.0.0
  type: puppet
  groups: [primary-controller, controller]
  requires: [fuel_pkgs]
  required_for: [globals]
  parameters:
    puppet_manifest: puppet/manifests/ovs_to_ns_ocf.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 120

- id: external-lb-ovs-to-ns-port-service
  version: 2.0.0
  type: puppet
  groups: [primary-controller, controller]
  requires: [deploy_start, cluster-vrouter]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: puppet/manifests/ovs_to_ns_service.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 600

# This is a workaround to disable adding record to hosts file if we use FQDN external host
- id: disable-public-ssl-hash
  version: 2.0.0
  type: puppet
  groups: [primary-controller, controller]
  requires: [ssl-add-trust-chain]
  required_for: [ssl-dns-setup]
  condition: "settings:public_ssl.horizon == true or settings:public_ssl.services == true"
  parameters:
    puppet_manifest: puppet/manifests/disable_public_ssl_hash.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 60

- id: enable-public-ssl-hash
  version: 2.0.0
  type: puppet
  groups: [primary-controller, controller]
  requires: [ssl-dns-setup]
  required_for: [hosts]
  condition: "settings:public_ssl.horizon == true or settings:public_ssl.services == true"
  parameters:
    puppet_manifest: puppet/manifests/enable_public_ssl_hash.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 60
